import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Partials/Header";
import isUserLoggedIn from "@/app/lib/auth";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const isLoggedIn = isUserLoggedIn();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header isLoggedIn={isLoggedIn} />
        {children}
      </body>
    </html>
  );
}
